//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarlingDBFreader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarlingDBFreader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000..007F; Basic Latin
        ///0080..00FF; Latin-1 Supplement
        ///0100..017F; Latin Extended-A
        ///0180..024F; Latin Extended-B
        ///0250..02AF; IPA Extensions
        ///02B0..02FF; Spacing Modifier Letters
        ///0300..036F; Combining Diacritical Marks
        ///0370..03FF; Greek and Coptic
        ///0400..04FF; Cyrillic
        ///0500..052F; Cyrillic Supplement
        ///0530..058F; Armenian
        ///0590..05FF; Hebrew
        ///0600..06FF; Arabic
        ///0700..074F; Syriac
        ///0750..077F; Arabic Supplement
        ///0780..07BF; Thaana
        ///07C0..07FF; NKo
        ///0800..083F; Samaritan
        ///0840..085F; Mandaic
        ///08A0..08F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnicodeBlocks {
            get {
                return ResourceManager.GetString("UnicodeBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UnicodeCharData_gzip {
            get {
                object obj = ResourceManager.GetObject("UnicodeCharData_gzip", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
