//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarlingDBFreader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool logTagFixing {
            get {
                return ((bool)(this["logTagFixing"]));
            }
            set {
                this["logTagFixing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>\B</string>
  <string>\b</string>
  <string>\B</string>
  <string>\b</string>
  <string>\I</string>
  <string>\i</string>
  <string>\I</string>
  <string>\i</string>
  <string>\U</string>
  <string>\u</string>
  <string>\U</string>
  <string>\u</string>
  <string>\H</string>
  <string>\h</string>
  <string>\H</string>
  <string>\h</string>
  <string>\L</string>
  <string>\l</string>
  <string>\L</string>
  <string>\l</string>
  <string>\C</string>
  <string>\c</string>
  <string>\C</string>
  <string>\c</string>
  <string>\X</string>
  <string>\x</string>
  <string>\X</string>
  <string>\x</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection tagCollection {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["tagCollection"]));
            }
            set {
                this["tagCollection"] = value;
            }
        }
    }
}
